# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71fc41a7cc35c8e746cb3792cebc5956284d5750dd578fb56f4c6592ec35fdc52e41cbdac9bd034cd85d91ee41f800a8b1aefc7316b1ec9305d09fbb20ca8c8c

test:
  secret_key_base: 608c2fa69f55b6960dc5f5c4afc938a00488aad8bc8096a259cf0ea486931551647b35a4f2913c2366e979fddff73649b9916752256ac1cc882f198c9ca99c2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
